# -*- coding: utf-8 -*-
"""Model_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckVdqvQpccg5B9WlUnICzvL6EIXoH8r_

# Downloading Libraries
"""

!pip install sentencepiece

! pip install datasets transformers seqeval

!pip install accelerate

"""# Loading Model

"""

!wget https://dl.fbaipublicfiles.com/biolm/RoBERTa-large-PM-M3-Voc-hf.tar.gz

!tar -xf RoBERTa-large-PM-M3-Voc-hf.tar.gz

task = "ner"
model_checkpoint = "/kaggle/working//RoBERTa-large-PM-M3-Voc/RoBERTa-large-PM-M3-Voc-hf"
batch_size = 4

"""## Loading the dataset"""

from datasets import load_dataset, load_metric

datasets = load_dataset("ktgiahieu/maccrobat2018_2020")
datasets = datasets['train'].train_test_split(test_size=0.1)

"""The `datasets` object itself is [`DatasetDict`](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasetdict), which contains one key for the training, validation and test set."""

datasets

from datasets import load_dataset,DatasetDict
import os
datasets = load_dataset("ktgiahieu/maccrobat2018_2020")
save_directory = "dataset"
datasets.save_to_disk(save_directory)

print(f"Dataset has been saved to {os.path.abspath(save_directory)}")
loaded_datasets = DatasetDict.load_from_disk(save_directory)
print(loaded_datasets)

"""Convert To Dataframe"""

import pandas as pd
datasets = load_dataset("ktgiahieu/maccrobat2018_2020")
df = pd.DataFrame(datasets['train'])

print(df["tokens"][0])

"""Remove Duplicates"""

sentsss=[]
tagsss=[]
count=0
for i in range(len(df["tokens"])):
    if df["tokens"][i] in sentsss:
        count+=1
    else:
        sentsss.append(df["tokens"][i])
        tagsss.append(df["tags"][i])

"""Created filtered tags based on previous results"""

df = pd.DataFrame({
    "tokens": sentsss,
    "tags": tagsss
})

filtered=["I-Sex","B-Sex","I-Age","B-Age","I-Clinical_event","B-Clinical_event", "I-Personal_background","B-Personal_background", "I-Sign_symptom", "B-Sign_symptom","I-Medication","B-Medication", "I-AGE", "B-AGE","I-Diagnostic_procedure","B-Diagnostic_procedure"]

dict_length={}
count=0
sum=0
for i in sentsss:
    count+=1
    dict_length[count]=len(i)
    sum+=len(i)
print("Average:",sum/count)
dict_length
lengths = list(dict_length.values())
import matplotlib.pyplot as plt
# Define bins
bins = [0, 512, max(lengths)]

# Create histogram
plt.figure(figsize=(10, 5))
plt.hist(lengths, bins=bins, edgecolor='black')
plt.title('Distribution of Sentence Lengths')
plt.xlabel('Sentence Length')
plt.ylabel('Number of Sentences')
plt.xticks([0, 512, max(lengths)])
plt.show()

"""Spliting Paragraphs into smaller chunks to reduce count to less than 512"""

sents=[]
sent=[]
tag=[]
tags=[]
i=0
a=0
stop=0
while i<len(df["tokens"]):
  sum=len(df["tokens"][i])
  half=sum//2
  a=0
  tag=[]
  sent=[]
  while a<half:
    if "." in df["tokens"][i][a] and len(df["tokens"][i][a])==1:
      stop=a
    a+=1

  for d in range(stop+1):
    sent.append(df["tokens"][i][d])
    if df["tags"][i][d] not in filtered:
        df["tags"][i][d]='O'
    tag.append(df["tags"][i][d])
  tags.append(tag)
  sents.append(sent)
  tag=[]
  sent=[]
  for d in range(stop+1,sum):
    sent.append(df["tokens"][i][d])
    if df["tags"][i][d] not in filtered:
        df["tags"][i][d]='O'
    tag.append(df["tags"][i][d])
  tags.append(tag)
  sents.append(sent)
  i+=1

"""Crosscheck split of data"""

a=0
for i in range(len(df["tokens"])):
  if len(df["tokens"][i])!=len(sents[a])+len(sents[a+1]) and len(sents[a])+len(sents[a+1])!=len(tags[a])+len(tags[a+1]):
    print(a,i)
    break
  a+=2

split_df = pd.DataFrame({"tokens": sents, "tags": tags})

# Write the DataFrame to a CSV file
split_df.to_csv("split_sentences_tags.csv", index=False)

dict_length={}
count=0
sum=0
for i in sents:
    count+=1
    dict_length[count]=len(i)
    sum+=len(i)
print("Average:",sum/count)
dict_length
lengths = list(dict_length.values())
import matplotlib.pyplot as plt

bins = [0, 512, max(lengths)]


plt.figure(figsize=(10, 5))
plt.hist(lengths, bins=bins, edgecolor='black')
plt.title('Distribution of Sentence Lengths')
plt.xlabel('Sentence Length')
plt.ylabel('Number of Sentences')
plt.xticks([0, 512, max(lengths)])
plt.show()

dict_tags={}
for labels in df["tags"]:
    for tag in labels:
        tag=tag.replace("B-","")
        tag=tag.replace("I-","")
        if 'O' in tag:
            continue
        if tag not in dict_tags:
            dict_tags[tag]=1
        else:
            dict_tags[tag]+=1

dict_tags

labels = list(dict_tags.keys())
counts = list(dict_tags.values())


plt.figure(figsize=(16, 8))
bars = plt.bar(labels, counts, color='blue')


for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval, int(yval), va='bottom')  # va: vertical alignment

plt.title('Distribution of Tags')
plt.xlabel('Labels')
plt.ylabel('Count')
plt.show()
#sex, clinical_event, personal_background, sign_symtom, Medication, AGE, Diagnostic_procedure

from datasets import Dataset, DatasetDict
data_dict = {
    "tokens": sents,
    "tags": tags
}
split_dataset = Dataset.from_dict(data_dict)

# Create a DatasetDict with the new Dataset
split_dataset_dict = DatasetDict({
    "train": split_dataset
})

print(split_dataset_dict)

datasets=split_dataset_dict

datasets = datasets['train'].train_test_split(test_size=0.1)

datasets

from datasets import Dataset, concatenate_datasets, Features, Sequence, Value
import pandas as pd

# Load synthetic data
synthetic_data = pd.read_csv("/kaggle/input/synthetic-dataset/synthetic_medical_ner_dataset.csv")

synthetic_data['tokens'] = synthetic_data['tokens'].apply(eval)
synthetic_data['tags'] = synthetic_data['tags'].apply(eval)

features = Features({
    'tokens': Sequence(feature=Value(dtype='string')),
    'tags': Sequence(feature=Value(dtype='string'))
})

synthetic_dataset = Dataset.from_pandas(synthetic_data, features=features)

updated_train_dataset = concatenate_datasets([datasets['train'], synthetic_dataset])

datasets['train'] = updated_train_dataset

datasets

from datasets import Dataset, ClassLabel, Value, DatasetDict

# Define the ClassLabel feature with the label names
label_list = filtered=["I-Sex","B-Sex","I-Age","B-Age","I-Clinical_event","B-Clinical_event", "I-Personal_background","B-Personal_background", "I-Sign_symptom", "B-Sign_symptom","I-Medication","B-Medication", "I-AGE", "B-AGE","I-Diagnostic_procedure","B-Diagnostic_procedure",'O']
# filtered_label_list = [
#     "B-Diagnostic_procedure", "I-Diagnostic_procedure", "B-Sign_symptom", "B-Lab_value",
#     "B-Biological_structure", "B-Detailed_description", "B-Disease_disorder", "B-Medication",
#     "B-Therapeutic_procedure", "I-Biological_structure", "I-Sign_symptom", "I-Date",
#     "I-History", "I-Disease_disorder", "I-Dosage", "I-Detailed_description"
# ]

# Create ClassLabel with the filtered list
label = ClassLabel(names=label_list)

# Function to map examples to the new numeric labels
# def map_labels(example):
#     return {
#         "tokens": example['tokens'],
#         "tags": example["tags"],
#         "numeric_tags": [label.encode_example(x) if x in filtered_label_list else 0 for x in example["tags"]],
#     }

# # Assuming you have a dataset called `datasets`
datasets = datasets.map(lambda example: {"tokens": example['tokens'],
    "tags": example["tags"],
    "numeric_tags": [label.encode_example(x) for x in example["tags"]],
})
# datasets = datasets.map(map_labels)

# datasets = datasets.map(lambda example: {"tokens": example['tokens'],
#     "tags": example["tags"],
#     "numeric_tags": [label.encode_example(x) for x in example["tags"]],
# })

# label_list=filtered_label_list

datasets

"""## Preprocessing the data"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, add_prefix_space=True)

import transformers
assert isinstance(tokenizer, transformers.PreTrainedTokenizerFast)

label_all_tokens = True

def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True, max_length=512)

    labels = []
    for i, label in enumerate(examples[f"numeric_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            # Special tokens have a word id that is None. We set the label to -100 so they are automatically
            # ignored in the loss function.
            if word_idx is None:
                label_ids.append(-100)
            # We set the label for the first token of each word.
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            # For the other tokens in a word, we set the label to either the current label or -100, depending on
            # the label_all_tokens flag.
            else:
                label_ids.append(label[word_idx] if label_all_tokens else -100)
            previous_word_idx = word_idx

        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

tokenized_datasets = datasets.map(tokenize_and_align_labels, batched=True)

"""## Fine-tuning the model"""

from transformers import AutoModelForTokenClassification, TrainingArguments, Trainer

model = AutoModelForTokenClassification.from_pretrained(model_checkpoint, num_labels=len(label_list))

# old_model= AutoModelForTokenClassification.from_pretrained(model_checkpoint)
# model= AutoModelForTokenClassification.from_pretrained("bert-base-uncased", num_labels=len(label_list))
# model.bert=old_model.bert

datasets['train'].shape

model_name = model_checkpoint.split("/")[-1]
args = TrainingArguments(
    f"{model_name}-finetuned-{task}",
    evaluation_strategy = "epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=7,
    weight_decay=0.01,
    lr_scheduler_type='cosine',
    report_to="wandb",
    push_to_hub=False,
)

from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer)

metric = load_metric("seqeval")

import numpy as np

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    # Remove ignored index (special tokens)
    true_predictions = [
        [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = metric.compute(predictions=true_predictions, references=true_labels)
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

trainer = Trainer(
    model,
    args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

"""Training Model"""

import wandb
wandb.init(
    name="test_1"
)

trainer.train()

"""Evaluating Model"""

trainer.evaluate()

predictions, labels, _ = trainer.predict(tokenized_datasets["test"])
predictions = np.argmax(predictions, axis=2)

# Remove ignored index (special tokens)
true_predictions = [
    [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
    for prediction, label in zip(predictions, labels)
]
true_labels = [
    [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
    for prediction, label in zip(predictions, labels)
]

results = metric.compute(predictions=true_predictions, references=true_labels)
results


#sex, clinical_event, personal_background, sign_symtom, Medication